### ISSUE TITLE
Can this be done as a GitHub fork?

### ISSUE THREAD

**Issue by chrisvest** [UniKnow/AsciiDoclet#1]
That way, the code history and lineage would be preserved, and it'd be possible to send pull requests between the forks.

**Comment by msche** [comment]
Hi Chrisvest, Been out of the running for a while. Could you explain exactly what you mean by this bug/issue?

**Comment by chrisvest** [comment]
I mean, this is based on the work I did, and the coffee I uploaded, but it preserves none of the git history, which makes it hard to pull your changes back up stream. Ideally all improvements should eventually find their way back to the original asciidoclet repository so people don't have to shop around to find which ever fork has the right features and level of support.
